# Sample setup macro for a simple AmBe simulation in WCTE

/run/verbose 1
/tracking/verbose 0
/hits/verbose 0
/grdm/verbose 0


###############
# GEOMETRY
###############

## select the geometry
## Use the WCTE geometry (16c4r from CAD)

/WCSim/mPMT/PMTtype_inner PMT3inchR14374_WCTE

/WCSim/WCgeom nuPRISMBeamTest_16cShort_mPMT

# Rotate barrel by half a tower (needed for correct WCTE geometry)
/WCSim/Geometry/RotateBarrelHalfTower true

# false --> new placement method, does not use replica in construction, place PMT one by one
/WCSim/PMT/ReplicaPlacement false

############################################################################################
## These comments are only useful when using
## /WCSim/PMT/ReplicaPlacement false

# Apply random fluctuation to PMT placement. Argument specifies the Gaussian 1 sigma value in 1D
# The fluctuation is applied at the last step of position calculation
/WCSim/PMT/PositionVariation 0 mm

# Change the ID radius at top, middle and bottom for PMT placement
# The PMT positions and directions are calculated such that the PMTs are always touching
# and perpendicular to the ID wall in the same (z,theta) coordinates
/WCSim/PMT/TankRadiusChange 0 0 0 mm

# Read PMT positions from input file. This overrides the auto positioning algorithm
#/WCSim/PMT/PositionFile /scratch/saborido/wcsim-dev/wcsim-install/data/mPMT_Position_WCTE.txt

# To import CDS into simulation (the arm that was used for placing the calibration sources inside the tank)
# 1. Download the CDS CAD model and set the path
# 2. Use the following PMT position file where 8 mPMTs are removed
/WCSim/Geometry/SetCDSFile /data/saborido/CDS_file/ArmV2.stl
/WCSim/PMT/PositionFile /scratch/saborido/wcsim-dev/wcsim-install/data/mPMT_Position_WCTE_CDS.txt
############################################################################################

##################
# MISCELLANEOUS
##################

# Studies in ~2022 suggest that SensitiveDetector_Only is the most correct
/WCSim/PMTQEMethod SensitiveDetector_Only

# turn on the collection efficiency
/WCSim/PMTCollEff on

# command to choose save or not save the pi0 info
/WCSim/SavePi0 false

##################
# AmBe CALIBRATION SOURCE
##################
# - BGO Placement: Default in source code is false. If set to true, you'll place the BGO inside
# the detector geometry at (0,0,0) position. This is only supported if you use ambeevt generator
# so you can see the tag scintillation light for the AmBe source.
/WCSim/BGOPlacement true

# Note that /WCSim/BGOPlacement *must* be set before /WCSim/Construct
#
# - BGO Position: Place the source in a different position using X, Y and Z coordinates
/WCSim/BGOPosition 0 0.305 0 m

# Needed for AmBe calibration:
# - save neutron capture information
# - deactivate nKiller so neutrons are not killed too early
/WCSim/SaveCapture true
#/process/inactivate nKiller # do NOT use this with FTFP_BERT_HP

# Set Gadolinium doping (concentration is in percent)
/WCSim/DopingConcentration 0.03 
/WCSim/DopedWater true

# Now actually build the geometry
/WCSim/Construct

##################
# DIGITISER & TRIGGER
##################

# choose the Trigger & Digitizer type
/DAQ/Digitizer SKI
/DAQ/Trigger NoTrigger
#/DAQ/Trigger NDigits

# grab the other DAQ options (thresholds, timing windows, etc.)
/control/execute macros/daq.mac

##################
# DARK NOISE (turned off)
##################

# There is an independent messenger class instance for each PMT type
# tank is the default one & is present in all geometries

/DarkRate/SetDetectorElement tank
/DarkRate/SetDarkRate 0 kHz

##################
# PHYSICS
##################
## It should be noted that only one /mygen/generator can be run
## at once.

# Or you can use the AmBe Calibration Source Generator.
# This launches two primary particles in a random direction from the source position:
# one neutron and one gamma.
# The energy of the gamma can be:
# - 4.4 MeV 65% of the time.
# - 7.7 MeV 8%  of the time.
# - 0.0 MeV 26% of the time.
# Neutron Energy is taken from a simulated realistic AmBe Spectrum depending on the Gamma Energy.
# In order to run this correctly, the AmBe source must be in the geometry & neutron capture
# must be activated - for details see the "AmBe CALIBRATION SOURCE" section above
/mygen/generator ambeevt


##################
# TRACKING
##################
## Commands to control which true particle tracks are tracked and saved to the output file:
## By default, save all tracks in the chain from primaries to those that produce Cherenkov photons that produce hits
/Tracking/saveHitProducingTracks true

## Due to the typically very large number of optical photons, a fraction can be tracked by setting the percentage to randomly draw
## Note that the value is a percentage from 0.0 to 100.0, not fraction 0.0 to 1.0
/Tracking/fractionOpticalPhotonsToDraw 0.0

##################
# OUTPUT
##################

## Boolean to select whether to save the NEUT RooTracker vertices in the output file
/WCSimIO/SaveRooTracker 0

## change the name of the output root file
/WCSimIO/RootFile OUTFILE_PLACEHOLDER

##################
# NUMBER OF EVENTS TO RUN
##################

/WCSim/random/seed SEED_PLACEHOLDER

/run/beamOn 40000
#exit